name: Static Analysis

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        go-version:
          - "1.21.x"
          - "1.22.x"
          - "1.23.x"
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Print staticcheck version
        run: staticcheck -version

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Run go vet
        run: go vet ./...
